spring.application.name=Gestion_des_evaluations
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_evaluations
spring.datasource.username=postgres
spring.datasource.password=2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=704a10010fa3ab18f13e389eb80accda0ae5d622741bcd1f28be58faac00e937ef454c522475b068a72ac4ec02b45c63cd327dafc89029c94a87da3c962b18ed
jwt.expiration=300000