package com.example.Gestion_des_evaluations.Action.Model;

public enum TypeAction {
    CREATION_UTILISATEUR,
    MODIFICATION_UTILISATEUR,
    DESACTIVATION_COMPTE,
    REACTIVATION_COMPTE,
    AFFECTATION_ROLE,
    RETRAIT_ROLE,

    VALIDATION_SUJET,
    REJET_SUJET,

    DEPOT_RECLAMATION,
    TRAITEMENT_RECLAMATION,
    SUPPRESSION_RECLAMATION,
    CREATION_SESSION_RECLAMATION,
    OUVERTURE_SESSION_RECLAMATION,
    FERMETURE_SESSION_RECLAMATION,

    CREATION_PROGRAMMATION,
    MODIFICATION_PROGRAMMATION,
    SUPPRESSION_PROGRAMMATION,

    DEPOT_NOTE,
    MODIFICATION_NOTE,
    SUPPRESSION_NOTE,

    SIGNALER_INCIDENT,
    TRAITER_INCIDENT,
    CLOTURER_INCIDENT,

    CREATION_EVALUATION,
    MODIFICATION_EVALUATION,
    CHANGEMENT_STATUT_EVALUATION,
    SUPPRESSION_EVALUATION,

    DEPOT_COPIE,
    MODIFICATION_COPIE,
    SUPPRESSION_COPIE,
    ATTRIBUTION_COPIE,
    RETRAIT_COPIE,
    DEPOT_COPIE_CORRIGEE,
    MISE_EN_CORRECTION,

    CONNEXION,
    DECONNEXION


}